### ISSUE TITLE
你好，非常喜欢go.readmorejoy.com搜索，现提几个建议。

### ISSUE THREAD

**Issue by Briy09** [luckrill/readmorejoy.com#1]
能否添加搜索结果中的搜索关键字高亮。谢谢！

**Comment by luckrill** [comment]
你的意思是 https://www.readmorejoy.com/search 这个吗？ 我实现的 站内搜索

关于 每个站的站内搜索，需要略微定制的，特定到这个网站

我给自己网站的站内搜索实现是：开发了一个网页链接，链接到自己网站就好

如果会写JS，自己直接封装实现，我自己不是特别擅长JS

go.readmorejoy.com 是搜索工具，其中的关键字，后台了使用不同的搜索引擎，每个搜索引擎对显示 关键字高亮的方式不同，自己偷懒，索性取消。

**Comment by Briy09** [comment]
是的，就是这个站内搜索。
> 开发了一个网页链接，链接到自己网站就好

那能否把这部分代码开源吗？
或者直接把 你自己**修改的有站内搜索的 hugo-theme-jane 主题**开源。
只需要把主题开源就行，一些涉及到隐私的部分可以放到私有库中。

另外关于关键字高亮，有一个mark.js能集成不？
https://markjs.io/
https://segmentfault.com/a/1190000019672267

**Comment by luckrill** [comment]
非常感谢，非常感谢
我的网站，几个月里一直开源的。
但是，始终是我一个人在做提交
后来，有若干功能要做商业化，就私有了
开发的功能越来越多，私有方便

**Comment by luckrill** [comment]
字符高亮，我可以直接在python脚本写一个函数实现，在这个需求里 更简单

**Comment by luckrill** [comment]
花了些功夫，实现了 关键字显亮

**Comment by Briy09** [comment]
看起来好些了：）关键字在内容中时可以高亮，但是关键字在标题中可能还无法高亮。
比如
https://www.readmorejoy.com/readmorejoy?who=gg&start=0&key=%E5%BC%80%E5%8F%91

**Comment by luckrill** [comment]
标题没有必要 关键字显亮。 大多数搜索引擎 标题不显亮。 百度 显亮
我看 标题没有必要的
